version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news_parsing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - news-parsing-app-network

networks:
  news-parsing-app-network:
    driver: bridge
